-- RETIRED: historical hard-coded stock reset.
-- Do not reapply old physical counts to today's inventory.
-- Use Bracket Inventory > Physical count with a fresh count and a reason.
-- Migration 0112 records selected types and their verification boundary
-- atomically. The historical script remains available in Git history only.
-- This file intentionally performs no database changes.
