-- RETIRED: historical order-status update followed by a separate stock credit.
-- Replaying that sequence can credit a delivery twice or leave a half-save.
-- Reconcile the old order against receipt evidence and physical counts.
-- Use Record receipt for new verified arrivals.
-- Historical implementation remains available in Git history only.
-- This file intentionally performs no database changes.
